# Generated by Django 3.0.5 on 2020-06-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
                ('payment_mode', models.CharField(blank=True, editable=False, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD'), ('UPI', 'UPI')], max_length=100)),
                ('bill_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Bill')),
                ('meter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=200)),
                ('house_address', models.CharField(max_length=300)),
                ('house_owner', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=300)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('NOT RESOLVED', 'NOT RESOLVED')], default='NOT RESOLVED', max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Bill')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Meter'),
        ),
    ]
