# Generated by Django 3.0.5 on 2020-05-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('generated_on', models.DateField()),
                ('paid_on', models.DateField(null=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD'), ('UPI', 'UPI')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('NOT RESOLVED', 'NOT RESOLVED')], default='NOT RESOLVED', max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.TransactionModels'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
