# Generated by Django 3.0.7 on 2020-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
