# Generated by Django 3.0.5 on 2020-05-20 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200520_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.UUIDField(default=uuid.UUID('ed53cf45-5bca-4cfc-821d-28b856cd914b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
