# Generated by Django 3.0.5 on 2020-05-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200510_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remarks',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
