# Generated by Django 3.0.5 on 2020-05-20 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200520_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.UUIDField(default=uuid.UUID('dd9f0df5-d864-460b-864f-ca2df0656dc7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
