# Generated by Django 3.0.5 on 2020-05-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20200511_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodels',
            name='bill_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Bill'),
        ),
        migrations.AddField(
            model_name='transactionmodels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
