# Generated by Django 3.0.5 on 2020-06-03 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200603_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.UUIDField(default=uuid.UUID('b87144a3-07ac-4408-b172-5bc18955cdf7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
